services:
  bash: &base
    build: .
    image: aawg-buildroot
    volumes:
      - .:/app
      - dl:/app/buildroot/dl
      - output:/app/buildroot/output
    working_dir: /app/buildroot
    command: bash

  generate_image_donotuse: &generate_image
    <<: *base
    command: bash -c "/app/build.sh $${BOARD_NAME}"

  rpi0w:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi0w

  rpi02w:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypizero2w

  rpi3a:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi3a

  rpi4:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi4

  rpi5:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi5

volumes:
  dl:
  output:
